const COMPANY_LAST_INDEX = 73;
const ADDRESS_LAST_INDEX = 153;
const ADDRESS_FIRST_INDEX = 73;
const COMPANY_FIRST_INDEX = 33;

export {
  COMPANY_LAST_INDEX,
  COMPANY_FIRST_INDEX,
  ADDRESS_FIRST_INDEX,
  ADDRESS_LAST_INDEX,
};
